spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newdb
    username: root
    password: mysql
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      fail-on-empty-beans: false
